#!/bin/zsh

btLineN=$(rfkill list | grep -n 'tpacpi' | cut -c 1)
btLineN=$btLineN',+1p'
wifiLineN=$(rfkill list | grep -n 'phy0' | cut -c 1)
wifiLineN=$wifiLineN',+1p'

bt=$(rfkill list | sed -n $btLineN | tr -d [:blank:] | tr -d '\n' | cut -z -c 1,22-31,43-)
wifi=$(rfkill list | sed -n $wifiLineN | tr -d [:blank:] | tr -d '\n' | cut -z -c 1,7-15,30-)

seleccion=$(echo -se $bt'\n'$wifi | dmenu -nf red -b green -sf red -fn 12)

if [[  echo $seleccion | grep -e 'no' ]]; then
    numNo=$(echo $seleccion | cut -c 1) 
    rfkill block $(echo $numNo)
    echo 'BLOQUEADO'

elif [[  echo $seleccion | grep -e 'yes' ]]; then
    numYes=$(echo $seleccion | cut -c 1) 
    rfkill unblock $(echo $numYes)
    echo 'DESBLOQUEADO'

else
  echo 'ESCAPE O EXCEPCIÓN NO CONTROLADA'
fi
